= Compound Types - Enums

link:./index.html[Table of Contents]

== Enums

`enum`s represent different variation of the same subject.

[.notes]
--
- stress that enums are an "either or" type: you can only have one variant at a time (you're not accumulating data as with structs)
- stress that you can only have the variants, not the enum itself (i.e. `Movement::Left`. but not `Movement`)
--

== Definition and Construction

[source,rust]
----
include::./6.rs[]
----

The different choices of Enums are called "variants."

== Enums with Values

[source,rust]
----
include::./7.rs[]
----

== Enums with Structured Variants

[.notes]
--
- each enum variant will be its *worst-case* size! (e.g. the size of its biggest member)

*possible interactive detour:*
- Q: what's the size of `Actions` on bytes?
    - correct A: 12, because we have a tagged union:

    ```pseudo-c
    struct {
        tag: u32 // discriminant is always u32 => 4 bytes
        data: union {
            stick_around: (), // 0 bytes
            move_to: tsruct{ x: i21, y: i32} // 4 bytes
        }
    }
    ```
--

[source,rust]
----
include::./8.rs[]
----

== `null`

Does not exist.

== `()`

[.notes]
--
- we often use this similarly to how you'd use `void` in C
--

The empty tuple `()` represents the absence of data.

[source,rust]
----
include::./9.rs[]
----

link:./index.html[Table of Contents]